### ISSUE TITLE
groupfolders.get_file_shares() boolean arguments are not recognized by the API

### ISSUE THREAD

**Issue by JocelynDelalande** [aaronsegura/nextcloud-async#26]
get_file_shares has two boolean args that are typed as boolean.

However, using :

`get_file_shares(folder, reshares=True, subfiles=True)`

… Won't work (the options are not honored)

On the other hand, using 

`get_file_shares(folder, reshares='true', subfiles='true')`

Will honor the arguments.

**Comment by aaronsegura** [comment]
Thank you for opening this issue.  I will issue a new release later today including the fix.

**Comment by aaronsegura** [comment]
https://pypi.org/project/nextcloud-async/0.0.8/

**Comment by JocelynDelalande** [comment]
You rocks, thanks :)
